// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZrMWM5uKcP1iv7KaQpGKU1MltmvNLqjM',
    appId: '1:173180867261:web:b6201a9193340217e75dd4',
    messagingSenderId: '173180867261',
    projectId: 'quick-split-bill-ee7f5',
    authDomain: 'quick-split-bill-ee7f5.firebaseapp.com',
    storageBucket: 'quick-split-bill-ee7f5.firebasestorage.app',
    measurementId: 'G-JCZJGRK7K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvmJOWgo3rVuzVrh64uMAVD_hOP4yPSwk',
    appId: '1:173180867261:android:89d8990a7136f271e75dd4',
    messagingSenderId: '173180867261',
    projectId: 'quick-split-bill-ee7f5',
    storageBucket: 'quick-split-bill-ee7f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYqSAZyaN9Ww7aO1IHn1W6NM9QHaajfB8',
    appId: '1:173180867261:ios:b8f808639786140fe75dd4',
    messagingSenderId: '173180867261',
    projectId: 'quick-split-bill-ee7f5',
    storageBucket: 'quick-split-bill-ee7f5.firebasestorage.app',
    iosBundleId: 'com.example.quickSplitBill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYqSAZyaN9Ww7aO1IHn1W6NM9QHaajfB8',
    appId: '1:173180867261:ios:b8f808639786140fe75dd4',
    messagingSenderId: '173180867261',
    projectId: 'quick-split-bill-ee7f5',
    storageBucket: 'quick-split-bill-ee7f5.firebasestorage.app',
    iosBundleId: 'com.example.quickSplitBill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZrMWM5uKcP1iv7KaQpGKU1MltmvNLqjM',
    appId: '1:173180867261:web:3a00a1847ebf8047e75dd4',
    messagingSenderId: '173180867261',
    projectId: 'quick-split-bill-ee7f5',
    authDomain: 'quick-split-bill-ee7f5.firebaseapp.com',
    storageBucket: 'quick-split-bill-ee7f5.firebasestorage.app',
    measurementId: 'G-LCX99SW253',
  );
}
